/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design system extraído de Stitch - Aeon Health
        'primary':                    '#114349',
        'on-primary':                 '#ffffff',
        'primary-container':          '#2d5a61',
        'on-primary-container':       '#a2d0d8',
        'primary-fixed':              '#bcebf3',
        'primary-fixed-dim':          '#a1ced6',
        'on-primary-fixed':           '#001f24',
        'on-primary-fixed-variant':   '#1f4d54',
        'inverse-primary':            '#a1ced6',
        'secondary':                  '#48626e',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#cbe7f5',
        'on-secondary-container':     '#4e6874',
        'secondary-fixed':            '#cbe7f5',
        'secondary-fixed-dim':        '#afcbd8',
        'on-secondary-fixed':         '#021f29',
        'on-secondary-fixed-variant': '#304a55',
        'tertiary':                   '#214337',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#395a4e',
        'on-tertiary-container':      '#abd0c0',
        'tertiary-fixed':             '#c6ebdb',
        'tertiary-fixed-dim':         '#aacebf',
        'on-tertiary-fixed':          '#002117',
        'on-tertiary-fixed-variant':  '#2c4d41',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'background':                 '#f4faff',
        'on-background':              '#111d23',
        'surface':                    '#f4faff',
        'on-surface':                 '#111d23',
        'surface-variant':            '#d7e4ec',
        'on-surface-variant':         '#404849',
        'surface-tint':               '#39656c',
        'surface-bright':             '#f4faff',
        'surface-dim':                '#cfdce4',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#e9f6fd',
        'surface-container':          '#e3f0f8',
        'surface-container-high':     '#ddeaf2',
        'surface-container-highest':  '#d7e4ec',
        'inverse-surface':            '#263238',
        'inverse-on-surface':         '#e6f3fb',
        'outline':                    '#71787a',
        'outline-variant':            '#c0c8c9',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body':     ['Inter', 'sans-serif'],
        'label':    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg':    '0.25rem',
        'xl':    '0.5rem',
        'full':  '0.75rem',
      },
    },
  },
  plugins: [],
}
